ALTER TABLE `Curso` ADD `foto` VARCHAR(150) NULL AFTER `descripcion`;
ALTER TABLE `Inscripcion` ADD `pagado` BOOLEAN NOT NULL DEFAULT FALSE AFTER `idCurso`;
ALTER TABLE `Participante` ADD `idCliente` INT NOT NULL AFTER `cargo`;


UPDATE `Route` SET `path` = '/editar-asociado' WHERE `Route`.`idRoute` = 7;
UPDATE `Route` SET `path` = '/ver-asociado' WHERE `Route`.`idRoute` = 68;
DELETE FROM `RolRoute` WHERE `RolRoute`.`idRoute` = 6;
DELETE FROM `Route` WHERE `Route`.`idRoute` = 62;
UPDATE `Route` SET `component` = '25' WHERE `Route`.`idRoute` = 5;
INSERT INTO `Route` (`idRoute`, `path`, `name`, `icon`, `component`, `layout`, `show`, `parent`, `parentId`) VALUES (NULL, '/asociado-calendario', 'Eventos', 'ni ni-calendar-grid-58 text-blue', '27', '/admin', '1', '0', '19');
DELETE FROM `Route` WHERE `Route`.`idRoute` = 51;
DELETE FROM `Route` WHERE `Route`.`idRoute` = 52;
DELETE FROM `Route` WHERE `Route`.`idRoute` = 53;
DELETE FROM `Route` WHERE `Route`.`idRoute` = 54;
DELETE FROM `Route` WHERE `Route`.`idRoute` = 55;
DELETE FROM `Route` WHERE `Route`.`idRoute` = 56;
DELETE FROM `Route` WHERE `Route`.`idRoute` = 50;
UPDATE `Route` SET `idRoute` = '50' WHERE `Route`.`idRoute` = 67;
UPDATE `Route` SET `parentId` = '45' WHERE `Route`.`idRoute` = 74;
Delete from RolRoute where idRoute=74;
UPDATE `Route` SET `name` = 'Eventos' WHERE `Route`.`idRoute` = 74;
INSERT INTO `RolRoute` (`idRolRoute`, `idRol`, `idRoute`) VALUES (NULL, '10', '41'), (NULL, '10', '6'), (NULL, '10', '57'), (NULL, '10', '68'), (NULL, '10', '10'), (NULL, '10', '42'), (NULL, '10', '58'), (NULL, '10', '18'), (NULL, '10', '45');
UPDATE `users` SET `rol` = '10' WHERE `users`.`idUsuario` in (3,11,18);
Delete from RolRoute where idRolRoute=99;
UPDATE `Route` SET `path` = '/ver-asociado/:id' WHERE `Route`.`idRoute` = 68;
UPDATE `Route` SET `path` = '/editar-asociado-sa/:id' WHERE `Route`.`idRoute` = 36;
UPDATE `Route` SET `path` = '/editar-asociado/:id' WHERE `Route`.`idRoute` = 7;
INSERT INTO `Route` (`idRoute`, `path`, `name`, `icon`, `component`, `layout`, `show`, `parent`, `parentId`) VALUES (NULL, '/ocurrencias', 'Ocurrencias', 'fa fa-handshake text-blue', '46', '/admin', '1', '0', '58');
INSERT INTO `RolRoute` (`idRolRoute`, `idRol`, `idRoute`) VALUES (NULL, '6', '68');
ALTER TABLE `Participante` CHANGE `idCliente` `idCliente` INT(11) NULL;
INSERT INTO `Route` (`idRoute`, `path`, `name`, `icon`, `component`, `layout`, `show`, `parent`, `parentId`) VALUES (NULL, '', 'Contabilidad', 'fa fa-calculator text-blue', '0', '/admin', '0', '1', '0');
INSERT INTO `RolRoute` (`idRolRoute`, `idRol`, `idRoute`) VALUES (NULL, '6', '79');
INSERT INTO `Route` (`idRoute`, `path`, `name`, `icon`, `component`, `layout`, `show`, `parent`, `parentId`) VALUES (NULL, '/contabilidad/pagos', 'Pagos ', 'fa fa-credit-card text-blue', '48', '/admin', '1', '0', '79');
INSERT INTO `Route` (`idRoute`, `path`, `name`, `icon`, `component`, `layout`, `show`, `parent`, `parentId`) VALUES (NULL, '', 'Cobranza', 'ni ni-credit-card text-blue', '0', '/admin', '0', '1', '0');
INSERT INTO `Route` (`idRoute`, `path`, `name`, `icon`, `component`, `layout`, `show`, `parent`, `parentId`) VALUES (NULL, '/cobranza-reportes', 'Dashboard', 'ni ni-chart-bar-32 text-blue', '42', '/admin', '1', '0', '81'), (NULL, '/cuentas', 'Cuentas', 'ni ni-credit-card text-blue', '49', '/admin', '1', '0', '81'), (NULL, '/membresias', 'Membresias', 'ni ni-calendar-grid-58 text-blue', '15', '/admin', '1', '0', '81'), (NULL, '/registro-emision', 'Nueva emisión', 'fa fa-file text-success', '13', '/admin', '0', '0', '81');
UPDATE `RolRoute` SET `idRoute` = '81' WHERE `RolRoute`.`idRolRoute` = 32;
UPDATE `users` SET `rol` = '11' WHERE `users`.`idUsuario` = 13;
INSERT INTO `RolRoute` (`idRolRoute`, `idRol`, `idRoute`) VALUES (NULL, '11', '41'), (NULL, '11', '57'), (NULL, '11', '42'), (NULL, '11', '81'), (NULL, '11', '10'), (NULL, '11', '18'), (NULL, '11', '79'), (NULL, '11', '45'), (NULL, '11', '68'), (NULL, '11', '66');
INSERT INTO `RolRoute` (`idRolRoute`, `idRol`, `idRoute`) VALUES (NULL, '4', '79');
