INSERT INTO `Route` (`idRoute`, `orderRoute`, `path`, `name`, icon, component, layout, `show`, parent, parentId) VALUES (NULL, NULL, '', 'Web', 'ni ni-palette text-blue', '0', '/admin', '1', '1', '0');
INSERT INTO `Route` (`idRoute`, `orderRoute`, `path`, `name`, icon, component, layout, `show`, parent, parentId) VALUES (NULL, NULL, '/web/noticias', 'Noticias', 'fas fa-newspaper text-blue', '55', '/admin', '1', '0', '99');
INSERT INTO RolRoute (idRolRoute, idRol, idRoute) VALUES (NULL, '8', '99');
INSERT INTO `Route` (`idRoute`, `orderRoute`, `path`, `name`, icon, component, layout, `show`, parent, parentId) VALUES (NULL, NULL, '/web/nueva-noticia', 'Nueva noticia', 'fas fa-newspaper text-blue', '56', '/admin', '0', '0', '99');

CREATE TABLE Noticia ( id INT NOT NULL AUTO_INCREMENT , fecha TIMESTAMP NULL , url VARCHAR(100) NOT NULL , miniatura TEXT NULL , titulo VARCHAR(200) NOT NULL , contenido TEXT NOT NULL , PRIMARY KEY (id));
ALTER TABLE Noticia ADD created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER contenido;
ALTER TABLE Noticia ADD updated_at TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER created_at;
INSERT INTO `Route` (`idRoute`, `orderRoute`, `path`, `name`, icon, component, layout, `show`, parent, parentId) VALUES (NULL, NULL, '/web/editar-noticia/:id', 'Editar noticia', 'ni ni-single-02 text-green', '56', '/admin', '0', '0', '99');
ALTER TABLE Curso ADD inWeb BOOLEAN NOT NULL DEFAULT FALSE AFTER estado;
INSERT INTO `Route` (`idRoute`, `orderRoute`, `path`, `name`, icon, component, layout, `show`, parent, parentId) VALUES (NULL, NULL, '/web/pronunciamientos', 'Pronunciamientos', 'fas fa-scroll text-blue', '57', '/admin', '1', '0', '99');
INSERT INTO `Route` (`idRoute`, `orderRoute`, `path`, `name`, icon, component, layout, `show`, parent, parentId) VALUES (NULL, NULL, '/web/nuevo-pronunciamiento', 'Nuevo pronunciamiento', 'fas fa-scroll text-blue', '58', '/admin', '0', '0', '99');
INSERT INTO `Route` (`idRoute`, `orderRoute`, `path`, `name`, icon, component, layout, `show`, parent, parentId) VALUES (NULL, NULL, '/web/editar-pronunciamiento/:id', 'Editar pronunciamiento', 'fas fa-scroll text-green', '58', '/admin', '0', '0', '99');
CREATE TABLE Pronunciamiento ( id INT NOT NULL AUTO_INCREMENT , titulo VARCHAR(100) NOT NULL , imagen TEXT NOT NULL , fecha TIMESTAMP NULL , PRIMARY KEY (id));
ALTER TABLE Pronunciamiento ADD created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER fecha;
ALTER TABLE Pronunciamiento ADD updated_at TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER created_at;
ALTER TABLE Noticia CHANGE fecha fecha DATE NULL DEFAULT NULL;
ALTER TABLE Pronunciamiento CHANGE fecha fecha DATE NULL DEFAULT NULL;
CREATE TABLE RevistaDigital ( id INT NOT NULL AUTO_INCREMENT , fecha DATE NULL , imagen TEXT NOT NULL , url VARCHAR(200) NULL , PRIMARY KEY (id));
ALTER TABLE RevistaDigital ADD created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER url;
ALTER TABLE RevistaDigital ADD updated_at TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER created_at;
ALTER TABLE RevistaDigital ADD active BOOLEAN NOT NULL DEFAULT TRUE AFTER url;
ALTER TABLE RevistaDigital CHANGE active active TINYINT(1) NOT NULL DEFAULT '0';
INSERT INTO `Route` (`idRoute`, `orderRoute`, `path`, `name`, icon, component, layout, `show`, parent, parentId) VALUES (NULL, NULL, '/web/revistasdigitales', 'Revistas', 'ni ni-single-copy-04 text-blue', '59', '/admin', '1', '0', '99');
INSERT INTO `Route` (`idRoute`, `orderRoute`, `path`, `name`, icon, component, layout, `show`, parent, parentId) VALUES (NULL, NULL, '/web/nueva-revista', 'Nueva revista', 'ni ni-single-copy-04 text-blue', '60', '/admin', '0', '0', '99');
INSERT INTO `Route` (`idRoute`, `orderRoute`, `path`, `name`, icon, component, layout, `show`, parent, parentId) VALUES (NULL, NULL, '/web/editar-revista/:id', 'Editar Revista Digital', 'ni ni-single-copy-04 text-green', '60', '/admin', '0', '0', '99');
ALTER TABLE `RevistaDigital` ADD `revista` TEXT NULL AFTER `imagen`;
INSERT INTO `Route` (`idRoute`, `orderRoute`, `path`, `name`, icon, component, layout, `show`, parent, parentId) VALUES (NULL, NULL, '/web/actividades', 'Actividades', 'ni ni-tie-bow text-blue', '61', '/admin', '1', '0', '99');
INSERT INTO `Route` (`idRoute`, `orderRoute`, `path`, `name`, icon, component, layout, `show`, parent, parentId) VALUES (NULL, NULL, '/web/nueva-actividad', 'Nueva actividad', 'ni ni-tie-bow text-blue', '62', '/admin', '0', '0', '99');
INSERT INTO `Route` (`idRoute`, `orderRoute`, `path`, `name`, icon, component, layout, `show`, parent, parentId) VALUES (NULL, NULL, '/web/editar-actividad/:id', 'Editar actividad', 'ni ni-tie-bow text-green', '62', '/admin', '0', '0', '99');
CREATE TABLE Actividad ( id INT NOT NULL AUTO_INCREMENT , titulo VARCHAR(100) NOT NULL , imagen TEXT NOT NULL , fecha TIMESTAMP NULL , PRIMARY KEY (id));
ALTER TABLE Actividad ADD created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER fecha;
ALTER TABLE Actividad ADD updated_at TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER created_at;
ALTER TABLE Actividad CHANGE fecha fecha DATE NULL DEFAULT NULL;
ALTER TABLE `Actividad` CHANGE `fecha` `fechaInicio` DATE NOT NULL;
ALTER TABLE `Actividad` ADD `fechaFin` DATE NOT NULL AFTER `fechaInicio`;